### ISSUE TITLE
Add support for http authentication

### ISSUE THREAD

**Issue by beeman** [beeman/static-server#1]
HTTP Authentication should be managed by setting a `username:password` key in the `HTTP_AUTH_PASSWORD` env variable and should be disabled if this env var does not exist.

See `protect` property here https://github.com/firebase/superstatic#superstaticoptions

**Comment by obrera** [comment]
This has been supported since the original version via `HTTP_AUTH_USER` and `HTTP_AUTH_PASS` environment variables. See the [README](https://github.com/beeman/static-server#configuration) for details.

**Comment by beeman** [comment]
For reference:

Create `compose.yaml`:

```yaml
services:
  web:
    image: beeman/static-server:latest
    volumes:
      - ./dist:/workspace/app:ro
    ports:
      - '9876:9876'
    environment:
      - HTTP_AUTH_USER=admin
      - HTTP_AUTH_PASS=secret
```

Run it:
```shell
mkdir dist
echo 'hello world' > dist/index.html
docker compose up
```
